"""
Report Router
PDF report generation for audit summaries
"""

from fastapi import APIRouter, Depends, Query, HTTPException
from fastapi.responses import FileResponse
from pathlib import Path
import logging
from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak
from reportlab.lib.units import inch
from datetime import datetime

from services.model_loader import get_companies_df, get_fraud_proba, get_graph_data
from routers.auth import get_current_user

router = APIRouter()
logger = logging.getLogger(__name__)

REPORTS_DIR = Path(__file__).parent.parent / "static_reports"
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

@router.get("/generate_pdf")
async def generate_pdf_report(
    gstin: str = Query(None, description="Generate report for specific GSTIN"),
    report_type: str = Query("summary", description="Type of report: summary, detailed, audit"),
    current_user: dict = Depends(get_current_user)
):
    """Generate PDF audit report"""
    try:
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"audit_report_{timestamp}.pdf"
        filepath = REPORTS_DIR / filename
        
        # Create PDF
        doc = SimpleDocTemplate(str(filepath), pagesize=letter)
        story = []
        styles = getSampleStyleSheet()
        
        # Title
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#114C5A'),
            spaceAfter=30
        )
        story.append(Paragraph("NETRA TAX - Fraud Detection Report", title_style))
        story.append(Spacer(1, 0.2*inch))
        
        # Report metadata
        story.append(Paragraph(f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", styles['Normal']))
        story.append(Paragraph(f"Generated by: {current_user.get('full_name', current_user.get('username'))}", styles['Normal']))
        story.append(Spacer(1, 0.3*inch))
        
        # Summary section
        companies_df = get_companies_df()
        fraud_proba = get_fraud_proba()
        graph_data = get_graph_data()
        
        if fraud_proba is not None and len(fraud_proba) > 0:
            high_risk = (fraud_proba > 0.7).sum()
            medium_risk = ((fraud_proba > 0.3) & (fraud_proba <= 0.7)).sum()
            low_risk = (fraud_proba <= 0.3).sum()
            
            summary_data = [
                ['Metric', 'Value'],
                ['Total Entities', str(len(fraud_proba))],
                ['High Risk', str(int(high_risk))],
                ['Medium Risk', str(int(medium_risk))],
                ['Low Risk', str(int(low_risk))],
                ['Average Fraud Score', f"{fraud_proba.mean() * 100:.2f}%"],
                ['Total Network Edges', str(int(graph_data.num_edges)) if graph_data else "0"]
            ]
            
            summary_table = Table(summary_data, colWidths=[3*inch, 2*inch])
            summary_table.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#114C5A')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('FONTSIZE', (0, 0), (-1, 0), 12),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                ('GRID', (0, 0), (-1, -1), 1, colors.black)
            ]))
            
            story.append(Paragraph("Executive Summary", styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
            story.append(summary_table)
            story.append(Spacer(1, 0.3*inch))
        
        # High-risk entities
        if gstin and companies_df is not None:
            story.append(Paragraph(f"Analysis for GSTIN: {gstin}", styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
            # Add specific entity analysis here
        else:
            story.append(Paragraph("High-Risk Entities", styles['Heading2']))
            story.append(Spacer(1, 0.2*inch))
            
            if companies_df is not None and fraud_proba is not None:
                high_risk_df = companies_df[fraud_proba > 0.7].head(10)
                if len(high_risk_df) > 0:
                    risk_data = [['GSTIN', 'Fraud Score', 'Location']]
                    for idx, row in high_risk_df.iterrows():
                        node_idx = companies_df.index.get_loc(idx)
                        if node_idx < len(fraud_proba):
                            risk_data.append([
                                str(row.get('company_id', 'N/A')),
                                f"{fraud_proba[node_idx] * 100:.2f}%",
                                str(row.get('location', 'N/A'))
                            ])
                    
                    risk_table = Table(risk_data, colWidths=[2*inch, 1.5*inch, 2*inch])
                    risk_table.setStyle(TableStyle([
                        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#FF9932')),
                        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                        ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                        ('GRID', (0, 0), (-1, -1), 1, colors.black)
                    ]))
                    story.append(risk_table)
        
        # Build PDF
        doc.build(story)
        
        return FileResponse(
            filepath,
            media_type='application/pdf',
            filename=filename
        )
    except Exception as e:
        logger.error(f"PDF generation error: {e}")
        raise HTTPException(status_code=500, detail=f"PDF generation error: {str(e)}")

